import React, { useState } from 'react';
import { Plus, Trash2, Play, Copy, Check, ArrowRight, Sparkles, Folder, FileImage, Shield, Archive } from 'lucide-react';

interface PipelineStepItem {
  id: string;
  type: 'ensure_dir' | 'filter_files' | 'resize_images' | 'watermark' | 'strip_exif' | 'create_archive' | 'find_duplicates';
  title: string;
  params: Record<string, any>;
}

export const PipelineBuilder: React.FC = () => {
  const [pipelineName, setPipelineName] = useState('Media Asset Ingestion & Sanitization');
  const [steps, setSteps] = useState<PipelineStepItem[]>([
    {
      id: 'step-1',
      type: 'ensure_dir',
      title: 'Ensure Output Directory',
      params: { path: './dist_processed' },
    },
    {
      id: 'step-2',
      type: 'resize_images',
      title: 'Batch Resize Images to 1080p',
      params: { max_dimension: 1080, format: 'webp' },
    },
    {
      id: 'step-3',
      type: 'strip_exif',
      title: 'Scrub EXIF & GPS Metadata',
      params: {},
    },
    {
      id: 'step-4',
      type: 'watermark',
      title: 'Apply Brand Watermark',
      params: { text: 'CONFIDENTIAL', position: 'bottom-right', opacity: 0.35 },
    },
    {
      id: 'step-5',
      type: 'create_archive',
      title: 'Bundle into Secure Zip Archive',
      params: { output: 'ready_assets.zip' },
    },
  ]);

  const [copiedScript, setCopiedScript] = useState(false);
  const [executionResult, setExecutionResult] = useState<{
    success: boolean;
    durationMs: number;
    stepsExecuted: number;
  } | null>(null);

  const availableStepTypes: Array<{
    type: PipelineStepItem['type'];
    label: string;
    description: string;
    defaultParams: Record<string, any>;
  }> = [
    {
      type: 'ensure_dir',
      label: 'Ensure / Create Directory',
      description: 'Recursively creates target folder hierarchy if missing.',
      defaultParams: { path: './output' },
    },
    {
      type: 'resize_images',
      label: 'Batch Resize Images',
      description: 'Lanczos scaling with aspect ratio lock.',
      defaultParams: { max_dimension: 1200, format: 'webp' },
    },
    {
      type: 'watermark',
      label: 'Apply Text Watermark',
      description: 'Stamps semi-transparent copyright text.',
      defaultParams: { text: '© 2026 PyToolkit', position: 'bottom-right', opacity: 0.4 },
    },
    {
      type: 'strip_exif',
      label: 'Strip EXIF & Privacy Tags',
      description: 'Scrubs GPS and hardware identifiers.',
      defaultParams: {},
    },
    {
      type: 'find_duplicates',
      label: 'Filter & Remove Duplicates',
      description: 'Computes SHA256 checksums to eliminate redundancy.',
      defaultParams: { algorithm: 'sha256' },
    },
    {
      type: 'create_archive',
      label: 'Create Compressed Zip Archive',
      description: 'Compresses outputs with Zip-Slip path validation.',
      defaultParams: { output: 'bundle.zip' },
    },
  ];

  const handleAddStep = (type: PipelineStepItem['type']) => {
    const template = availableStepTypes.find((s) => s.type === type);
    if (!template) return;
    const newStep: PipelineStepItem = {
      id: `step-${Date.now()}`,
      type,
      title: template.label,
      params: { ...template.defaultParams },
    };
    setSteps([...steps, newStep]);
  };

  const handleRemoveStep = (id: string) => {
    setSteps(steps.filter((s) => s.id !== id));
  };

  const handleRunSimulation = () => {
    setExecutionResult(null);
    setTimeout(() => {
      setExecutionResult({
        success: true,
        durationMs: Math.round(18 + steps.length * 7.4),
        stepsExecuted: steps.length,
      });
    }, 400);
  };

  // Generate Python Code
  const generatedPythonCode = `"""
Pipeline: ${pipelineName}
Auto-generated by PyToolkit Studio
"""

from pathlib import Path
from pytoolkit.directories import ensure_dir
from pytoolkit.files import create_archive, find_duplicates
from pytoolkit.images import (
    batch_resize_images,
    add_watermark,
    strip_exif_metadata,
)
from pytoolkit.pipelines import Pipeline


def build_pipeline() -> Pipeline:
    pipeline = Pipeline("${pipelineName}")
${steps
  .map((step, idx) => {
    if (step.type === 'ensure_dir') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: {"target_dir": ensure_dir("${step.params.path || './output'}")},
        name="${step.title}"
    )`;
    }
    if (step.type === 'resize_images') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: {"resized": batch_resize_images(
            ctx.get("files", []),
            max_dimension=${step.params.max_dimension || 1080},
            output_dir=ctx.get("target_dir")
        )},
        name="${step.title}"
    )`;
    }
    if (step.type === 'strip_exif') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: [strip_exif_metadata(f, output_dir=ctx.get("target_dir")) for f in ctx.get("resized", ctx.get("files", []))],
        name="${step.title}"
    )`;
    }
    if (step.type === 'watermark') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: [add_watermark(
            f,
            watermark_text="${step.params.text || 'CONFIDENTIAL'}",
            position="${step.params.position || 'bottom-right'}",
            opacity=${step.params.opacity || 0.35}
        ) for f in ctx.get("resized", ctx.get("files", []))],
        name="${step.title}"
    )`;
    }
    if (step.type === 'find_duplicates') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: {"duplicates": find_duplicates(ctx.get("target_dir", "."))},
        name="${step.title}"
    )`;
    }
    if (step.type === 'create_archive') {
      return `
    # Step ${idx + 1}: ${step.title}
    pipeline.add(
        lambda ctx: {"archive": create_archive(
            [ctx.get("target_dir", "./output")],
            "${step.params.output || 'bundle.zip'}"
        )},
        name="${step.title}"
    )`;
    }
    return '';
  })
  .join('\n')}

    return pipeline


if __name__ == "__main__":
    pipe = build_pipeline()
    result = pipe.run(initial_context={"files": list(Path("./input_photos").glob("*.jpg"))})
    print(f"Pipeline finished successfully: {result['success']} in {result['total_duration_ms']}ms")
`;

  const handleCopyScript = () => {
    navigator.clipboard.writeText(generatedPythonCode);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs text-slate-500 font-mono">
            <span>pytoolkit.pipelines</span>
            <span aria-hidden="true">·</span>
            <span>Composable Task Orchestration</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white mt-1.5">
            Visual Pipeline Composer
          </h1>
          <p className="text-sm text-slate-400 mt-1 max-w-2xl">
            Chain directory checks, batch image resizers, EXIF sanitization, and zip archiving into an executable Python pipeline script.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleRunSimulation}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-slate-950 bg-gradient-to-r from-cyan-400 to-blue-500 hover:from-cyan-300 hover:to-blue-400 rounded-lg shadow-sm transition-all active:scale-95"
          >
            <Play className="w-3.5 h-3.5 fill-current" />
            Dry-Run Pipeline
          </button>
        </div>
      </div>

      {executionResult && (
        <div className="p-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400">
              <Check className="w-4 h-4" />
            </div>
            <div>
              <div className="text-xs font-bold text-emerald-300">
                Dry-Run Simulation Succeeded
              </div>
              <div className="text-[11px] text-slate-400">
                Executed {executionResult.stepsExecuted} steps seamlessly in {executionResult.durationMs}ms
              </div>
            </div>
          </div>
          <span className="text-xs font-mono text-emerald-400">Status 200 OK</span>
        </div>
      )}

      {/* Main Grid: Pipeline Step Flow & Generated Code */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Column: Visual Step Sequence */}
        <div className="lg:col-span-6 space-y-4">
          <div className="p-4 bg-slate-900/80 border border-slate-800 rounded-2xl space-y-3">
            <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
              Pipeline Name
            </div>
            <input
              type="text"
              value={pipelineName}
              onChange={(e) => setPipelineName(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white font-semibold focus:outline-none focus:border-cyan-500"
            />
          </div>

          {/* Sequential Step Cards */}
          <div className="space-y-3">
            {steps.map((step, index) => (
              <div
                key={step.id}
                className="p-4 bg-slate-900 border border-slate-800 hover:border-slate-700/80 rounded-2xl flex items-start justify-between gap-3 transition-colors group"
              >
                <div className="flex items-start gap-3">
                  <div className="h-6 w-6 rounded-full bg-slate-800 flex items-center justify-center text-xs font-mono font-bold text-cyan-400 shrink-0 mt-0.5">
                    {index + 1}
                  </div>
                  <div className="space-y-1">
                    <div className="text-xs font-bold text-slate-200">{step.title}</div>
                    <div className="text-[11px] font-mono text-slate-400">
                      {step.type}({JSON.stringify(step.params)})
                    </div>
                  </div>
                </div>

                <button
                  onClick={() => handleRemoveStep(step.id)}
                  className="text-slate-600 hover:text-rose-400 p-1 rounded-lg transition-colors"
                  title="Remove Step"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>

          {/* Add Step Selector */}
          <div className="p-4 bg-slate-900/40 border border-dashed border-slate-800 rounded-2xl space-y-3">
            <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
              Add Pipeline Procedure
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {availableStepTypes.map((item) => (
                <button
                  key={item.type}
                  onClick={() => handleAddStep(item.type)}
                  className="p-2.5 bg-slate-950 hover:bg-slate-800/80 border border-slate-800 hover:border-cyan-500/40 rounded-xl text-left transition-all"
                >
                  <div className="text-xs font-bold text-slate-200">{item.label}</div>
                  <div className="text-[10px] text-slate-500 truncate mt-0.5">{item.description}</div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Generated Python Script */}
        <div className="lg:col-span-6 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl sticky top-24">
          <div className="px-5 py-3.5 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-300 uppercase tracking-wider">
              Generated Python Script
            </span>
            <button
              onClick={handleCopyScript}
              className="inline-flex items-center gap-1.5 px-3 py-1 text-xs font-medium text-slate-300 hover:text-white bg-slate-900 hover:bg-slate-800 border border-slate-700 rounded-lg transition-colors"
            >
              {copiedScript ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedScript ? 'Copied' : 'Copy Python Script'}
            </button>
          </div>

          <div className="p-4 bg-slate-950/80 font-mono text-xs text-slate-300 overflow-x-auto max-h-[600px]">
            <pre>{generatedPythonCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
